using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace WebConsole.Models
{
    public class PythonIDEViewModel
    {
        public string RunCode(string code, string param)
        {
            string cmd = string.Format("-c \""+ code + "\"");
            //string cmd = string.Format("-c \"import sys;print(sys.path);a=2;b=3;c=a+b;print('result='+str(c));\"");
            #region 支持手动输入
            //Console.WriteLine("请输入");
            //string input = Console.ReadLine();
            //cmd = string.Format("-c \""+input+"\"");
            #endregion
            string result = run_cmd("python.exe", cmd);
            return result;
        }

        /// <summary>
        /// 调用cmd命令
        /// </summary>
        /// <param name="program"></param>
        /// <param name="cmd"></param>
        /// <returns></returns>
        public static string run_cmd(string program, string cmd)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = program;
            start.Arguments = cmd;
            start.UseShellExecute = false;          // Do not use OS shell
            start.CreateNoWindow = true;            // We don't need new window
            start.RedirectStandardOutput = true;    // Any output, generated by application will be redirected back
            start.RedirectStandardError = true;     // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string result = process.StandardError.ReadToEnd();
                    if (result == null || result == "")
                    {
                        result = reader.ReadToEnd();
                    }
                    return result;
                }
            }
        }
    }
}
